### ISSUE TITLE
AppDelegate를 추가하는 방법은 없을까요?

### ISSUE THREAD

**Issue by leo6104** [GwonHyeok/ionic-plugin-naver#1]
private project로 개발해뒀던게 있어서 오픈소스가 없으면 공개할까 했는데 이미 이렇게 잘 만들어져있었군요 :) 

잘 쓰겠습니다. :) 

phonegap-plugin-push의 경우, 
AppDelegate+notification.h, AppDelegate+notification.m를 구성하고 plugin.xml에 source file태그로 추가해줬던데,

이런 방법으로는 AppDelegate에 넣어줘야한다는 코드를 패키지 설치했을 때 자동으로 되게 할 수 없을까요?

**Comment by GwonHyeok** [comment]
안녕하세요!
Method Swizzling 을 이용하면 직접 AppDelegate 에 추가하지 않고 사용이 가능하긴 합니다.
페이스북 로그인이나 구글 플러스 로그인의 경우 Method Swizzling을 이용하여 AppDelegate를 직접 수정하지 않고
사용가능하게 만들었더라고요 

해당 작업을 하고싶었지만 아직 작업을 하지 못했습니다
