### ISSUE TITLE
no value for name 에러 

### ISSUE THREAD

**Issue by kotran88** [GwonHyeok/ionic-plugin-naver#2]
로그인 성공후, requestMe()를 바로 불러서 개인정보를 가져오려고하는데...거기서 catch로 넘어가면서
no value for name이라는 에러가 뜹니다. alert부분에서...

doLogin() {
    this.naver.login()
      .then(response => {
        alert(response.accessToken);
        this.naver.requestMe()
        .then(response => {
          alert(response)
          alert(JSON.stringify(response));
        }) // 성공
        .catch(error => {alert("sss"+error)}); // 실패
    
      })
      .catch(error => console.error(error));
  }

**Comment by GwonHyeok** [comment]
안녕하세요 저 같은 경우는 다음과 같이 사용하였습니다.

```
    this.naver.login()
      .then(({ accessToken }) => new Promise(resolve => {
        this.naver.requestMe().then(naverMe => resolve(Object.assign({}, naverMe, { accessToken })))
      }))
      .then(({ accessToken, response }) => {
        const { profileImage, name, email } = response;
        return this.authProvider.loginNaver(accessToken, profileImage, name, email).map(res => res.json()).toPromise();
      })
      .then(this.loginSuccessCallback.bind(this))
      .catch(error => console.error(error));

```

**Comment by kotran88** [comment]
감사합니다 ㅎㅎ 수정해서 잘 사용했고 안드로이드는 되는거 확인했습니다~!
답변 달릴까..?라며 질문드렸는데...감사해요.

이제 곧 아이폰으로 네이버 로그인을 할건데 대충 읽어보고 url scheme은 설정했습니다.
xcode는 처음인데..
appdelegate에 추가하는 코드부분에 대해서 여쭤볼께요
<img width="255" alt="2017-10-09 9 32 56" src="https://user-images.githubusercontent.com/20656932/31338283-80428326-ad39-11e7-8c9c-ee6d171dbf2e.png">

appdelegate가 여러가지가 있는데 어디에 코드를 추가해야할까요? 

정말 감사합니다! ^^

**Comment by GwonHyeok** [comment]
@kotran88 
해결 하셨나요?

**Comment by kotran88** [comment]
appdelegate.h에 추가 안하고 해봤는데 되네요...
그런데..위에 알려주신 코드에서
this.authProvider
this.loginSuccessCallback
은 그냥 타입을 any로 하고 해도 되나요?

**Comment by GwonHyeok** [comment]
Duplicate of #5 

곧 수정되어서 업데이트될 예정 입니다.
