### ISSUE TITLE
라이선스 표시

### ISSUE THREAD

**Issue by HubKing** [GwonHyeok/ionic-plugin-naver#3]
안녕하세요?
사용하기 편리한 라이브러리를 공개해 주셔서 감사합니다. 그런데 제 앱에 사용하려니 라이선스 (licence) 관련 조항이 없네요. 명시해 주시면 제 앱의 오픈소스  크레디트에 표시하려고 합니다.

**Comment by GwonHyeok** [comment]
@HubKing 안녕하세요 License 항목 업데이트 해놓았습니다. 감사합니다
