### ISSUE TITLE
no value for name 에러

### ISSUE THREAD

**Issue by KimDae-Youn** [GwonHyeok/ionic-plugin-naver#5]
안녕하세요.
ionic-plugin-naver  getting-start 도중 아직까지 원인모를 no value for name 에러 때문에 진도가 안나가져서요..

            this.naver.login().then(res => {
                
                alert("로그인 - " + JSON.stringify(res));
                    
                this.naver.requestMe().then(res => {
                    alert("로그인 정보 - " + JSON.stringify(res));
                }).catch(err => {alert(err);});
            }).catch(err => {alert(err);});

이렇게 돌려본 결과
login 의 callback인
alert("로그인 - " + JSON.stringify(res));
만 돌고 그 다음인 requestMe의 결과는 애러인 catch로 돌아오고 그걸 alert로 확인해본 결과
no value for name 만... 나옵니다..
이유를 몰라서 해결도 안나오네요.. ㅠ

밑 이슈의 방법대로 따라해도 같은결과입니다.
에초에 requestMe 메소드에서 catch문으로 나가져서 아무 반응이 없어요..

**Comment by KimDae-Youn** [comment]
해결 했습니다..
NaverPlugin.java 에서
184라인에 buildRequestMeJsonObject 메소드가 잘못돼서 나는 에러였습니다..
따라서 그줄 없애고
			            JSONObject jsonObject = new JSONObject(response.toString());	
			            callbackContext.success(jsonObject.getJSONObject("response"));    
로 대체했습니다.
잘 나오네요..
안되시는분들 참고하세요.
수고하세요~

******************
참고로 NaverPlugin.java 파일을 수정 후 적용 시키려면
ionic cordova platform rm (android or ios)
후 빌드 하시기 바랍니다.

**Comment by GwonHyeok** [comment]
답변 감사합니다. 
제가 name 항목이 필수 값 인줄 알고 작업을 해서 발생한 문제 같습니다.
해당 문제 수정해서 곧 푸시 하겠습니다.

감사합니다.

**Comment by GwonHyeok** [comment]
1.0.3 버전으로 업데이트 되었습니다.
감사합니다.

[https://github.com/GwonHyeok/cordova-plugin-naver/commit/cabf6bde3aa61e1c9244d0888aceadc7c5361217](https://github.com/GwonHyeok/cordova-plugin-naver/commit/cabf6bde3aa61e1c9244d0888aceadc7c5361217)
